### ISSUE TITLE
unable to create backup

### ISSUE THREAD

**Issue by thinkJD** [elsbrock/edgerouter-backup#1]
Seems  like there is a problem with the go binary. 
Do I need some external dependencys on my EdgeRouter-x ?

```
ubnt@ubnt:/$ ./config/user-data/hooks/03-config-backup.sh

./config/user-data/hooks/03-config-backup.sh: line 30: /config/user-data/bin/go-ghwrite: 
cannot execute binary file: Exec format error
backup done
```

**Comment by elsbrock** [comment]
Thanks, could you share `uname -a`? I guess the -X is running another architecture.

**Comment by elsbrock** [comment]
Running `curl -sL https://github.com/elsbrock/go-ghwrite/releases/latest/download/go-ghwrite_linux-$(uname -m).tar.gz | tar xvzf - -C /config/user-data/bin/` should fix this, let me know.

**Comment by thinkJD** [comment]
Sorry for the late response :) 
Something is still broken. Maybe artefacts from the last try?
Or it is all good and I dont use it right.

```
ubnt@ubnt:~$ uname -a
Linux ubnt 4.14.54-UBNT #1 SMP Thu Mar 5 16:54:37 UTC 2020 mips GNU/Linux
ubnt@ubnt:~$ curl -sL https://github.com/elsbrock/go-ghwrite/releases/latest/download/go-ghwrite_linux-$(uname -m).tar.gz | tar xvzf - -C /config/user-data/bin/
go-ghwrite
ubnt@ubnt:~$ /config/user-data/hooks/03-config-backup.sh
/config/user-data/hooks/03-config-backup.sh: line 30: /config/user-data/bin/go-ghwrite: cannot execute binary file: Exec format error
backup done
```

**Comment by elsbrock** [comment]
Can you do `/config/user-data/bin/go-ghwrite`?

**Comment by rovo89** [comment]
It works on EdgeRouter-X-SFP after recompiling `go-ghwrite` with:
`GOOS=linux GOARCH=mipsle go build .`

Found the hint here: https://community.ui.com/questions/Golang-support-on-ER-X/7dd19ca6-3eee-4bb6-a4c6-8e5ea0fb37a0
Unfortunately `uname -m` returns `mips`, so not sure how to choose the correct binary automatically...

**Comment by elsbrock** [comment]
Great, thanks for the info! I will update the instructions later.
